version: '2'
services:
    eshop-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/eshop/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=eshop
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
